name: MAIN Generate Number

on:
  schedule:
    - cron: "0 * * * *"   # Runs every hour
  workflow_dispatch:       # Allow manual run

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Run script
        run: python test.py

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add numbers.txt
          git commit -m "Add number [skip ci]" || echo "No changes to commit"
          git push
